### ISSUE TITLE
can add Cover Art Archive support?

### ISSUE THREAD

**Issue by jonm58** [greendoescode/vlc-rpc#54]
https://coverartarchive.org
idk,just ask

**Comment by sdasda7777** [comment]
I think it most likely could be done. @GreenDiscord Want to take a look at it?

**Comment by GreenDiscord** [comment]
> I think it most likely could be done. @GreenDiscord Want to take a look at it?

I've had a look before, I believe you need to get an mbid or something like that (which is musicbrainz song IDs) It's something like that, if need to find a way of getting the mbid.

**Comment by sdasda7777** [comment]
It seems that tracks may have their own MBID as a metadata. Otherwise, there is this search API: https://musicbrainz.org/doc/MusicBrainz_API/Search

**Comment by GreenDiscord** [comment]
I'll get onto this soon then, It should've been quite easy with how the album art formatting works now.

**Comment by GreenDiscord** [comment]
> It seems that tracks may have their own MBID as a metadata. Otherwise, there is this search API: https://musicbrainz.org/doc/MusicBrainz_API/Search

Most of my tracks do, I use MusicBrainz to add metadata to my music files. I have thought of somehow intergrating an auto metadata adding software to vlc-rpc, but its bulky and strays away from the main purpose.
