### ISSUE TITLE
Apple Music search API broken?

### ISSUE THREAD

**Issue by jonm58** [greendoescode/vlc-rpc#59]
![图片](https://github.com/user-attachments/assets/78ac0aa0-efb7-4626-a1f0-f8931c3fb4b3)
![图片](https://github.com/user-attachments/assets/5f8e117f-3e33-46ce-b698-fb71dce3642f)
I don't have any network issues.
I can download to 1.txt file from the link in the second image
https://itunes.apple.com/search?media=music&term=%E3%83%88%E3%82%B2%E3%83%8A%E3%82%B7%E3%83%88% E3%82%B2%E3%82%A2%E3%83%AA+%E5%90%8D%E3%82%82%E3%81%AA%E3%81%8D%E4%BD%95%E3% 82%82%E3%81%8B%E3%82%82

**Comment by greendoescode** [comment]
Hey thanks, it looks like they have changed it slighlty

**Comment by greendoescode** [comment]
Gimme a sec, gonna figure it out

**Comment by greendoescode** [comment]
I don't have any issues my end, can you send me the file your using?
I have discord (imgreenonline) if it helps.

**Comment by greendoescode** [comment]
Very confused on this @sdasda7777, Seems like a possible edgecase upstream though.

**Comment by sdasda7777** [comment]
I think I remember there being some issues when the search term is too long or something. I would probably recommend just using Cover Art Archive in the cases that don't work. (Might be worth it to include more information on this in the readme)

**Comment by greendoescode** [comment]
> I think I remember there being some issues when the search term is too long or something. I would probably recommend just using Cover Art Archive in the cases that don't work. (Might be worth it to include more information on this in the readme)

The thing is, it worked perfectly fine for me with the exact same file. Confusing me just a bit

**Comment by jonm58** [comment]
![图片](https://github.com/user-attachments/assets/b164cf27-f087-45dd-80b0-5f72544c1a74)
Wrong picure
![1](https://f4.bcbits.com/img/a2054452395_3.jpg)
[My searches on Apple Music](https://music.apple.com/album/re-%E7%B5%90%E6%9D%9F%E3%83%90%E3%83%B3%E3%83%89-ep/1759525321)
![Re:結束バンド - EP](https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/b7/45/a1/b745a1d0-0a0a-f90b-da14-f03d6c61fbb8/4534530153616.jpg/592x592bb.png)

**Comment by jonm58** [comment]
My itunes.apple.com can only use http2, http1.1 cannot be used.

**Comment by sdasda7777** [comment]
> The thing is, it worked perfectly fine for me with the exact same file. Confusing me just a bit

It could be basically anything, such as different servers, or servers in different locations, running with different software versions or locale or something. I really don't think it's something we should worry about. I'd say either Apple as a source just works for you (I suspect this will be the case for the most people) or it doesn't, or you want extra customization, and then you should probably use Cover Art Archive.

> Wrong picure

Best I can suggest is to look for the correct cover on Musicbrainz and then tag the track with the release ID.

**Comment by greendoescode** [comment]
yep, I think it's just an upstream issue that we can't deal with. Should I close this issue? 
I will add more info to the readme

**Comment by sdasda7777** [comment]
I think so, honestly

**Comment by greendoescode** [comment]
#11 was also the same issue, iirc
