### ISSUE TITLE
Can't even start the bat file..

### ISSUE THREAD

**Issue by Fenius64** [greendoescode/vlc-rpc#60]
Did not detect local Node.js executable, attempting to use `npm`...

> vlc-rpc@1.3.0 start
> node --trace-deprecation ./src/app.js

node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'vlc.js'
Require stack:
- C:\Users\harau\OneDrive\Documents\VLC-RPC\src\helpers\lager.js
- C:\Users\harau\OneDrive\Documents\VLC-RPC\src\app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\harau\OneDrive\Documents\VLC-RPC\src\helpers\lager.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\harau\\OneDrive\\Documents\\VLC-RPC\\src\\helpers\\lager.js',
    'C:\\Users\\harau\\OneDrive\\Documents\\VLC-RPC\\src\\app.js'
  ]
}

Node.js v20.17.0

this is the error i get when starting the bat, and yes i do have node js installed and the executable working fine, doing npm ci in the same folder prompts me with another log:

npm error code 1
npm error git dep preparation failed
npm error command C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\harau\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm error > register-scheme@0.0.2 install
npm error > node-gyp rebuild
npm error npm warn using --force Recommended protections disabled.
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@20.17.0 | win32 | x64
npm error gyp info find Python using Python version 3.12.5 found at "C:\Users\harau\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe"
npm error gyp http GET https://nodejs.org/download/release/v20.17.0/node-v20.17.0-headers.tar.gz
npm error gyp http 200 https://nodejs.org/download/release/v20.17.0/node-v20.17.0-headers.tar.gz
npm error gyp http GET https://nodejs.org/download/release/v20.17.0/SHASUMS256.txt
npm error gyp http GET https://nodejs.org/download/release/v20.17.0/win-x64/node.lib
npm error gyp http 200 https://nodejs.org/download/release/v20.17.0/SHASUMS256.txt
npm error gyp http 200 https://nodejs.org/download/release/v20.17.0/win-x64/node.lib
npm error gyp ERR! find VS
npm error gyp ERR! find VS msvs_version not set from command line or npm config
npm error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
npm error gyp ERR! find VS
npm error gyp ERR! find VS Failure details: undefined
npm error gyp ERR! find VS checking VS2022 (17.10.35027.167) found at:
npm error gyp ERR! find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm error gyp ERR! find VS - "Visual Studio C++ core features" missing
npm error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
npm error gyp ERR! find VS
npm error gyp ERR! find VS Failure details: undefined
npm error gyp ERR! find VS unsupported version "17.10.35027.167" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm error gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm error gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
npm error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm error gyp ERR! find VS
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS You need to install the latest version of Visual Studio
npm error gyp ERR! find VS including the "Desktop development with C++" workload.
npm error gyp ERR! find VS For more information consult the documentation at:
npm error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm error gyp ERR! stack at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:116:11)
npm error gyp ERR! stack at VisualStudioFinder.findVisualStudio (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:72:17)
npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm error gyp ERR! stack at async createBuildDir (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:95:26)
npm error gyp ERR! stack at async run (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:81:18)
npm error gyp ERR! System Windows_NT 10.0.19045
npm error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm error gyp ERR! cwd C:\Users\harau\AppData\Local\npm-cache\_cacache\tmp\git-clonewDbZQk
npm error gyp ERR! node -v v20.17.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm error npm error code 1
npm error npm error path C:\Users\harau\AppData\Local\npm-cache\_cacache\tmp\git-clonewDbZQk
npm error npm error command failed
npm error npm error command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm error npm error A complete log of this run can be found in: C:\Users\harau\AppData\Local\npm-cache\_logs\2024-09-01T20_56_24_702Z-debug-0.log
npm error A complete log of this run can be found in: C:\Users\harau\AppData\Local\npm-cache\_logs\2024-09-01T20_56_22_744Z-debug-0.log

any help please? it would be appreciated if possible, and i can't installl Visual Studio due to storage issues.

**Comment by sdasda7777** [comment]
Did you clone the repository or download some of the packaged versions?

**Comment by Fenius64** [comment]
> Did you clone the repository or download some of the packaged versions?

i downloaded one of the versions from the releases section, so no

**Comment by Fenius64** [comment]
ok so apprently there was an issue, one of the releases had no node_modules and no node.exe on the folder whatsoever and i think that caused the issue.

**Comment by sdasda7777** [comment]
I recall now, there is something funky going on with the release pipeline. I don't have time to look into it now, but I'm reopening the issue not to forget.

**Comment by greendoescode** [comment]
Do you have any info on the funkyness? I can have a look.

**Comment by sdasda7777** [comment]
It's just that the stable releases are not being built, in contrast to the nightly builds. Only the code of the stable releases gets released, downloading which is basically like cloning the repo (no node executable, no node modules). I think you might be able to figure it out, but don't worry about it if you don't.

**Comment by greendoescode** [comment]
I believe I've done something.. used the packager you used for nightly builds. have a look if you'd like.

**Comment by sdasda7777** [comment]
That looks almost correct, however the latest stable release still seems to be 1.3.0 which doesn't have the builds, and the 1.3.1 is marked as pre-release. Seems like you just need to tweak these parameters:

https://github.com/greendoescode/vlc-rpc/blob/e27571d099ab95c25d8436206f0feb8c7ffeb937/.github/workflows/release.yml#L56-L68

**Comment by greendoescode** [comment]
I set it as pre-release so you could edit it after the action created, to add a bigger description. I thought about maybe making an action to upload when a release is made aswell

**Comment by sdasda7777** [comment]
That looks good, good job!

**Comment by greendoescode** [comment]
Do you consider this issue finished now?
